name: Claude Assistant
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned, labeled]
  pull_request_review:
    types: [submitted]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    environment: claude-prod
    if: |
      # ... (既存のif文はそのまま)
    
    steps:
      # この部分を追加！
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全履歴を取得
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trigger_phrase: "@claude"
          assignee_trigger: "hokar3361"
          label_trigger: "claude-approved"
          max_turns: "5"
          timeout_minutes: 10
          model: "claude-4-opus"
